--------------------------------------------------------
--  DDL for Table TEMP_SAT_BK
--------------------------------------------------------

  CREATE TABLE "AIZAVALA"."TEMP_SAT_BK" 
   (	"ID_PERSONA" VARCHAR2(26 BYTE), 
	"NOMBRE" VARCHAR2(4000 BYTE), 
	"PATERNO" VARCHAR2(4000 BYTE), 
	"MATERNO" VARCHAR2(4000 BYTE), 
	"RFC" VARCHAR2(4000 BYTE), 
	"FECHA_NACIMIENTO" VARCHAR2(26 BYTE), 
	"LISTA" VARCHAR2(26 BYTE), 
	"ESTATUS" VARCHAR2(26 BYTE), 
	"IDDISPO" NUMBER(26,0), 
	"RAZONSOC" VARCHAR2(4000 BYTE), 
	"NOMBRECOMP" VARCHAR2(4000 BYTE), 
	"APELLIDOS" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 15106048 MINEXTENTS 1 MAXEXTENTS 1017
  PCTINCREASE 20 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_ACSELSEP" ;
